const SAVE_LIST = "film/SAVE_LIST";
const UPDATE_LOADING = "film/UPDATE_LOADING";
const SELECT_FILM = "film/SELECT_FILM";
const UPDATE_FILTER = "film/UPDATE_FILTER"

export default {
    SAVE_LIST,
    UPDATE_LOADING,
    SELECT_FILM,
    UPDATE_FILTER
};